services:
  postgres:
    image: "postgres:latest"
    env_file:
      - .env
    ports:
      - "5432:5432"
  api:
    image: "shopping_cart_api:latest"
    env_file:
      - .env
    ports:
      - "8000:8000"